export const favoriteProjects = [
  {
    id: 1,
    name: "Chikiliga",
    full_name: "user/chikiliga",
    html_url: "https://github.com/user/chiquiliga-frontend",
    front_demo_url: "https://chikilga.netlify.app/",
    back_demo_url: "https://chikiliga-back.onrender.com/",
    api_docs: "https://chikiliga-back.onrender.com/docs",
    language: "TypeScript & Python",
    description:
      "Chiquiliga is a fantasy football league application that integrates web scraping to provide real-time player statistics.",
    technologies: [
      "Vue 3",
      "Pinia",
      "Vite",
      "TypeScript",
      "TailwindCSS",
      "Chart.js",
      "FastAPI",
      "MongoDB",
      "Selenium",
      "BeautifulSoup",
      "Pydantic",
    ],
    image_url: "/images/chikliliga.png",
    highlights: [
      "Frontend developed with Vue 3 for a reactive and modular UI",
      "Pinia for efficient state management across the app",
      "TailwindCSS for rapid and modern styling",
      "Chart.js integration for displaying football player statistics dynamically",
      "FastAPI backend for high-performance API handling",
      "MongoDB as a flexible NoSQL database to store player data",
      "Web Scraping using Selenium and BeautifulSoup to fetch real-time player data",
      "Pydantic for robust data validation and serialization",
      "Deployed with Vite for optimized build performance",
    ],
  },
  {
    id: 2,
    name: "Filmly",
    full_name: "user/filmly",
    html_url: "https://github.com/JSSatorres/filmly",
    demo_url: "https://filmly-jss.onrender.com/",
    language: "TypeScript",
    description:
      "Movie and series search application using Vue 3, Pinia, and Axios.",
    technologies: ["Vue 3", "Pinia", "Axios", "Vite", "TypeScript", "SCSS"],
    image_url: "/images/filmly.png",
    highlights: [
      "Uses Vue 3 and Vite for fast performance",
      "Global state management with Pinia",
      "API consumption with Axios",
      "Optimized interface with SCSS",
    ],
  },
  {
    id: 3,
    name: "Tutorial SolidWorks",
    full_name: "www.tutorialsolidworks.es",
    html_url: "https://www.tutorialsolidworks.es",
    language: "WordPress",
    description:
      "An e-learning website for SolidWorks tutorials built with WordPress using Elementor and various plugins.",
    technologies: ["WordPress", "Elementor", "Plugins"],
    image_url: "/images/tutorialsolidworks.png",
    highlights: [
      "Built with WordPress for easy content management",
      "Uses Elementor for custom page building without coding",
      "Various plugins for enhanced functionality",
      "Supports payments with Stripe and PayPal",
    ],
  },
]
